apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dittnav-event-aggregator
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: dittnav-event-aggregator-secrets
    - secret: influxdb-credentials
  image: {{version}}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 30
  readiness:
    path: /internal/isReady
    initialDelay: 30
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  ingresses:
    - "https://dittnav-event-aggregator-gcp.nais.oera.no"
  webproxy: true
  resources:
    limits:
      cpu: "3"
      memory: 2400Mi
    requests:
      cpu: "1"
      memory: 2048Mi
  gcp:
    sqlInstances:
      - name: brukernotifikasjon-cache
        type: POSTGRES_11
        tier: db-n1-standard-2
        diskType: SSD
        highAvailability: true
        diskSize: 100
        diskAutoresize: true
        autoBackupTime: "03:00"
        databases:
          - name: brukernotifikasjon-cache
            envVarPrefix: DB
        maintenanceWindow:
          day: 1
          hour: 4
        cascadingDelete: false
  kafka:
    pool: nav-prod
  accessPolicy:
    outbound:
      external:
        - host: kafka-schema-registry.nais.adeo.no
