apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dittnav-event-aggregator
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: dittnav-event-aggregator-secrets
    - secret: influxdb-credentials
  image: {{version}}
  port: 8080
  liveness:
    path: /isalive
    initialDelay: 30
  readiness:
    path: /isready
    initialDelay: 30
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  webproxy: true
  resources:
    limits:
      cpu: "3"
      memory: 2400Mi
    requests:
      cpu: "100m"
      memory: 512Mi
  gcp:
    sqlInstances:
      - name: brukernotifikasjon-cache
        type: POSTGRES_11
        tier: db-custom-4-24576
        diskType: SSD
        highAvailability: true
        diskSize: 100
        diskAutoresize: true
        autoBackupTime: "03:00"
        databases:
          - name: brukernotifikasjon-cache
            envVarPrefix: DB
        maintenanceWindow:
          day: 1
          hour: 4
        cascadingDelete: false
  kafka:
    pool: nav-prod
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: kafka-schema-registry.nais.adeo.no
    inbound:
      rules:
        - application: dittnav-api
        - application: tms-varselbjelle-api
        - application: tms-min-side-proxy