apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dittnav-event-aggregator
  namespace: default
  labels:
    team: personbruker
spec:
  image: navikt/dittnav-event-aggregator:0.0.12
  team: personbruker
  port: 8080
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isAlive
    initialDelay: 5
  prometheus:
    path: /metrics
  replicas:
    min: 2
    max: 4
  ingresses:
    - "https://dittnav-event-aggregator.dev-sbs.nais.io"
  vault:
    enabled: true
  env:
    - name: IKKE_SENSITIV_PROPERTY
      value: uniktPerNaisManifest
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
