apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dittnav-event-aggregator
  namespace: default
  labels:
    team: personbruker
spec:
  image: navikt/dittnav-event-aggregator:0.0.14
  team: personbruker
  port: 8080
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  prometheus:
    path: /metrics
  replicas:
    min: 1
    max: 2
  ingresses:
    - "https://dittnav-event-aggregator.dev-sbs.nais.io"
  vault:
    enabled: true
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: "SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443"
    - name: KAFKA_SCHEMAREGISTRY_SERVERS
      value: "https://kafka-schema-registry.nais-q.adeo.no"
    - name: GROUP_ID
      value: "dittnav-aggregator-alpha-001"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
