apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dittnav-event-aggregator
  namespace: q1
  labels:
    team: {{team}}
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  prometheus:
    path: /metrics
  replicas:
    min: 2
    max: 4
  ingresses:
    - "https://dittnav-event-aggregator.dev-sbs.nais.io"
  vault:
    enabled: true
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: "SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443"
    - name: KAFKA_SCHEMAREGISTRY_SERVERS
      value: "https://kafka-schema-registry.nais-q.adeo.no"
    - name: GROUP_ID
      value: "dittnav-aggregator-alpha-001"
    - name: DB_NAME
      value: "dittnav-event-cache-preprod"
    - name: DB_HOST
      value: "b27dbvl008.preprod.local:5432"
    - name: DB_MOUNT_PATH
      value: "postgresql/preprod-fss"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
