apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dittnav-event-aggregator
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 5
  readiness:
    path: /internal/isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  ingresses:
    - "https://dittnav-event-aggregator.dev.nav.no"
  vault:
    enabled: true
    paths:
      - kvPath: /kv/preprod/sbs/dittnav-event-aggregator/personbruker
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /serviceuser/data/dev/srvdn-e-aggregator
        mountPath: /secret/serviceuser
  resources:
    limits:
      cpu: "3"
      memory: 2400Mi
    requests:
      cpu: "100"
      memory: 512Mi
