name: Deploy eksisterende versjon

on:
  repository_dispatch:
    types: deploy

env:
  VERSION: ${{ github.event.client_payload.version }}
  CLUSTER: ${{ github.event.client_payload.cluster }}
  NAMESPACE: ${{ github.event.client_payload.namespace }}

jobs:
  deploy:

    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Sjekk ut koden for dette repo-et'
        uses: 'actions/checkout@v2'

      - name: 'Sjekker ut commiten tilhørende imaget som skal deploy-es, for å få tak i riktig versjon av nais-mainifetene'
        run: |
          echo "Henter ut alle branch-er"
          git fetch --prune origin +refs/heads/*:refs/remotes/origin/*
          SHA=$(echo $VERSION | cut -c16-23)
          git checkout $SHA

      - name: 'Gjør klar nødvendige parametere for deploy til Nais'
        run: |
          APP_NAME="${GITHUB_REPOSITORY//navikt\//}"
          IMAGE_BASE="docker.pkg.github.com/$GITHUB_REPOSITORY/$APP_NAME"
          echo "::set-env name=IMAGE::$IMAGE_BASE:$VERSION"
          echo "::set-env name=CURRENT_REF::$(git log -1 --pretty='%H')"

      - name: 'Deploy-er til ${{ env.NAMESPACE }} i ${{ env.CLUSTER }}'
        uses: 'nais/deploy/actions/deploy@v1'
        env:
          REF: ${{ env.CURRENT_REF }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ env.CLUSTER }}
          RESOURCE: ./nais/nais.yaml
          VARS: ./nais/${{ env.CLUSTER }}/${{ env.NAMESPACE }}.json
          VAR: version=${{ env.IMAGE }}
          PRINT_PAYLOAD: true